# Generated by Django 4.2.1 on 2023-05-24 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='like',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='home.blogmodel'),
        ),
    ]
